site_name: John Stairs
site_url: https://john-stairs.github.io/documentation/
theme:
  name: material
  logo: img/logo_embedded.png
  favicon: img/favicon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - navigation.sections
    - navigation.instant
nav:
  - index.md
  - overview.md
  - RPG Camera:
      - rpg-camera/introduction.md
      - rpg-camera/demo.md
      - Getting Started:
        - rpg-camera/getting-started/project-setup.md
        - rpg-camera/getting-started/scene-setup.md
        - rpg-camera/getting-started/video.md
      - rpg-camera/useful-interfaces.md
      - rpg-camera/other-render-pipelines.md
      - rpg-camera/faq.md
      - rpg-camera/version-history.md
  - RPG Cameras & Controllers:
      - rpg-cameras-and-controllers/introduction.md
      - rpg-cameras-and-controllers/demo.md
      - Getting Started:
        - rpg-cameras-and-controllers/getting-started/project-setup.md
        - rpg-cameras-and-controllers/getting-started/scene-setup.md
        - rpg-cameras-and-controllers/getting-started/integrations.md
        - rpg-cameras-and-controllers/getting-started/videos.md
      - Components:
        - rpg-cameras-and-controllers/components/rpg-camera.md
        - rpg-cameras-and-controllers/components/rpg-view-frustum.md
        - rpg-cameras-and-controllers/components/rpg-motors.md
      - rpg-cameras-and-controllers/useful-interfaces.md
      - rpg-cameras-and-controllers/faq.md
      - rpg-cameras-and-controllers/version-history.md
  - RTS Camera:
      - rts-camera/introduction.md
      - rts-camera/demo.md
      - rts-camera/getting-started.md
      - rts-camera/input-handling.md
      - rts-camera/useful-resources.md
  - Planet Platformer Controller:
      - planet-platformer-controller/introduction.md
      - planet-platformer-controller/demo.md
      - Getting Started:
        - planet-platformer-controller/getting-started/project-setup.md
        - planet-platformer-controller/getting-started/scene-setup.md
      - planet-platformer-controller/physics-engine.md
      - planet-platformer-controller/helpful-tools.md
      - planet-platformer-controller/faq.md
      - planet-platformer-controller/version-history.md
  - feature-matrix.md
  - faq.md
  - roadmap.md
  - contact.md
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  plugins:
  - privacy:
      enabled: !ENV [CI, false]
  social:
    - icon: fontawesome/brands/unity 
      link: https://assetstore.unity.com/publishers/1799
      name: John Stairs on Unity's Asset Store
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@johnstairs7246
      name: John Stairs on YouTube
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2026 John Stairs | <a href="/documentation/imprint/">Imprint</a>