site_name: John Stairs's documentation
site_url: https://john-stairs.github.io/documentation/
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - navigation.footer
    - navigation.sections
    - navigation.instant
nav:
  - index.md
  - overview.md
  - RPG Camera:
      - rpg-camera/introduction.md
      - Getting Started:
        - rpg-camera/getting-started/project-setup.md
        - rpg-camera/getting-started/scene-setup.md
        - rpg-camera/getting-started/video.md
      - rpg-camera/useful-interfaces.md
      - rpg-camera/other-render-pipelines.md
      - rpg-camera/version-history.md
  - RTS Camera:
      - rts-camera/introduction.md
  - imprint.md
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  plugins:
  - privacy:
      enabled: !ENV [CI, false]
  social:
    - icon: fontawesome/brands/unity 
      link: https://assetstore.unity.com/publishers/1799
      name: John Stairs on Unity's Asset Store
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@johnstairs7246
      name: John Stairs on YouTube
copyright: Copyright &copy; 2025 John Stairs | <a href="imprint.html">Imprint</a>